### ISSUE TITLE
Adding tests to pass PkgEval

### ISSUE THREAD

**Issue by kimikage** [appleparan/OpenColor.jl#1]
Thank you for creating a nice package.

I am concerned about the lack of testing on this package. Of course, the main part of this package is the constant definitions, so there is little need to test it. However, the lack of a test has put this package on the failure list of PkgEval report.
e.g.: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2021-04/10/OpenColor.1.7.0-DEV-fc69c9aef3.log

Also, this is off-topic, but what about integrating the Open Color schemes into [ColorSchemes.jl](https://github.com/JuliaGraphics/ColorSchemes.jl)?

**Comment by kimikage** [comment]
Please consider this if you are so inclined.

**Comment by appleparan** [comment]
Thank you for informing me about that! I missed the notification, sorry for that.

Like you said, I thought it doesn't need a test because it is just constant definitions.
For now, I will add empty tests not to get PkgEval failure.
 
and.. about [ColorSchemes.jl](https://github.com/JuliaGraphics/ColorSchemes.jl), I will consider it.

**Comment by appleparan** [comment]
I close this because of [new release](https://github.com/appleparan/OpenColor.jl/releases/tag/v0.2.0)
